
let nameWord={
    "Kyrie,Irving":"Big Heart",
    "DeMar,DeRozan":"No.1 Kobe Fan",
    "LeBron,James":"Empire",
    "Giannis,Antetokounmpo":"Mr.Letter",
    "Jimmy,Butler":"Jordan's son？",
    "Stephen,Curry":"From Downtown",
    "James,Harden":"Euro Step",
    "Kevin,Durant":"For champion?",
    "Kawhi,Leonard":"No expression",
    "Anthony,Davis":"Mr.Eyebrows",
    "John,Wall":"Fastest Guard",
    "Isaiah,Thomas":"Best 175",
    "Kyle,Lowry":"Injury",
    "Paul,George":"New shoes",
    "Kevin,Love":"best family name",
    "Russell,Westbrook":"Non human",
    "Klay,Thompson":"God thom",
    "Draymond,Green":"Tough defence",
    "Marc,Gasol":"The Spinach Brother",
    "Dwyane,Wade":"Thunder",
    "Carmelo,Anthony":"Sweetie of apple",
    "Kobe,Bryant":"Mamba",
    "Blake,Griffin":"Slam dunk",
    "Tim,Duncan":"Bank shot",
    "Dirk,Nowitzki":"Grestest international",
    "Pau,Gasol":"The Spinach Brother",
    "Chris,Paul":"Speed",
    "Dwight,Howard":"Beast",
    "Tony,Parker":"Frendch speedie",
    "Rajon,Rondo":"Can him shot?",
    "Paul,Pierce":"Faith",
    "Steve,Nash":"no looking pass",
    "Derrick,Rose":"son of wind",
    "Manu,Ginóbili":"Argentina hawk",
    "Allen,Iverson":"Answer"
};
let commonWrod = ["wallpaper","king kong","game show","greatness",
"shoe size","autograph","liverpool","lion logo","old shoes","biography",
"education","eye color","questions","quiz 2016","qualities","interview",
"i promise","rotoworld","net worth","new shoes","years pro",
"usa shoes","ellie day","the block","quotes by","disney xd",
"update on","usa today","father of","family of","photos of",
"rotoworld","rap about","crossover","space jam","the shoes",
"old shoes","jim brown","jordan vs","height of","instagram",
"is injury","new shoes","net worth","is clutch","ethnicity","extension",
"cyberface","childhood","hand size","hairstyle","last name","languages",
"last game","autograph","dunk 2017","rotoworld","overrated","interview",
"instagram","potential","shoe size","shoe deal","years pro","yesterday",
"zach lowe","wallpaper","jersey uk","vs knicks","instagram","espn body",
"jump shot","vs lebron","lebron on","2k rating","nba hands","nba draft","height of",
"is 7 feet","pronounce","net worth","nba draft","grantland","instagram","odessa tx","nashville","net worth","nightclub",
"nba stats","images of","wrestling","wikipedia","instagram","interview","autograph","grizzlies","draft net","nba draft",
"net worth","nba stats","lsu stats","rotoworld","reference","nba draft","instagram","barcelona","biography","interview",
"reference","rotoworld","net worth","suns sign","net worth","instagram","nba stats","wikipedia","instagram","foamposite",
"best dunks","eurobasket","euroleague","highlights","okc jersey","uncle drew","underneath","is retired","kryptonate",
"kay felder","underrated","restaurant","glen davis","did retire","lamar odom","leaves nba","best dunks","video dunk",
"in the nfl","in college","top blocks","does start","al b. sure","holy cross","basketball","bear clark","buffalo mn",
"copywriter","highlights","ohio state","pittsburgh","nba salary","sacramento","daughter","jr grade","headband","game log",
"football","as a kid","olympics","on trump","contract","children","birthday","earnings","earrings","xiii low","xi shoes",
"nickname","position","pictures","wingspan","wife age","yo gotti","vertical","essay on","the wall","quien es","xbox one",
"facebook","contract","the diet","my house","yo gotti","house of","when was","can dunk","contract","wingspan","facebook",
"earnings","birthday","game log","all star","military","religion","orthodox","vertical","position","phonetic","siblings","zaragoza","warriors","snapchat","deadspin","is greek","nba 2k15","nba 2k16","nba 2k14","is black","nba vote","nickname","nba 2k17","did grew","facebook","baseball","brooklyn","football","contract","obituary","musician","poohtang","producer","clippers","wrestler","zimbabwe","linkedin","and wife","aldridge","eisbären","marriage","mackolik","maçkolik","aldridge","oklahoma","contract","comeback","d league","verletzt","nba 2k15","lsu team","lsu dunk","where is","nba news","daughter","arkansas","facebook","football","birthday","interviu","contract","maçkolik","mackolik","transfer","released","wingspan","vertical","vikipedi","clarence","game log","where is","bebasket","nbadraft","facebook","zip code","x reader","mackolik","maçkolik","as a baby","nba stats","cleveland","shoe size","slam dunk","rotoworld","reference","quits nba","jump ball","jump shot","last game","last team","wallpaper","instagram","interview","why trade","team 2k17","best game","best team","nba trade","wrestling","net worth","instagram","contracts","insurance","olathe ks","odessa tx","jp morgan","vancouver","rochester","utah jazz","minnesota","north bay","neurology","nba stats","drawing","son age","address","overall","college","mansion","muscles","brother","records","parents","workout","wedding","witness","youtube","uniform","twitter","tattoos","tv show","quiz on","zapatos","life of","beyonce","best of","cars of","drawing","twitter","the kid","tattoos","youtube","news on","what is","is dead","brother","fathead","cartoon","celtics","haircut","defense","mixtape","overall","is from","vs heat","parents","profile","youtube","twitter","t shirt","talking","workout","website","kobe on","is good","is hurt","nigeria","twitter","hip hop","designs","drummer","chicago","married","myspace","referee","retired","nba bio","jordans","twitter","tv host","wizards","succezz","youtube","amnesty","memphis","germany","unicaja","youtube","vikings","nba bio","hornets","raptors","twitter","tattoos","tribune","wedding","spotrac","surgery","twitter","twitter","fantasy","brother","maccabi","married","to suns","raptors","defense","phoenix","parents","youtube","raptors","twitter","youtube","eurocup","youtube","twitter","twitter","football","filipino","facebook","and shaq","earnings","estatura","nba team","d league","delaware","on bulls","vertical","pelicans","position","playoffs","contract","comeback","seahawks","game log","yao ming","released","xinjiang","wingspan","warriors","the trio","can dunk","training","tel aviv","flat top","nba dunk","shooting","linkedin","baseball","bruisers","attorney","cs lewis","computer","football","facebook","tampa fl","softball","obituary","victoria","randstad","pictures","mckinsey","wrestler","salary","knicks","jersey","jacket","height","game 7","father","family","finals","awards","lakers","legacy","outfit","crying","career","mother","quotes","images","income","retire","number","zimbio","zoom 1","zoom 3","points","poster","powder","violin","update","eminem","game 6","zimbio","zappos","lakers","forbes","poster","prince","reddit","record","rookie","ritual","age of","son of","salary","my way","jersey","who is","how is","top 10","family","height","greece","growth","lakers","length","lebron","muscle","mother","rookie","reddit","rating","origin","injury","images","poster","points","salary","top 10","travel","zimbio","quotes","future","update","upside","knicks","jersey","top 10","realgm","who is","number","simeon","salary","depaul","rapper","robbed","videos","jodeci","zodiac","family","mother","boosie","blocks","realgm","knicks","height","lakers","rivals","salary","height","family","moscow","macabi","tattoo","top 10","knicks","realgm","rivals","russia","waived","sixers","jersey","vaikas","who is","quotes","realgm","sixers","knicks","basket","salary","realgm","jersey","quotes","temple","average","haircut","how old","old man","overall","vs nets","vs shaq","parents","college","celtics","quartet","spotrac","retired","youtube","jordans","workout","twitter","thunder","tattoos","twitter","bastrop","bendigo","atlanta","calgary","indiana","houston","tolkien","toronto","youtube","memphis","wedding","wichita","shoes","stats","house","draft","games","facts","agent","movie","block","beard","email","emoji","xiiii","irish","rings","pizza","worth","young","yahoo","video","vogue","email","trade","trump","games","queen","vine","funny","pizza","beats","video","vogue","about","draft","stats","miami","james","young","hands","draft","facts","funny","block","house","greek","agent","memes","reach","obama","voice","video","shoes","shirt","story","yahoo","young","trade","forum","bucks","stats","house","stats","spurs","chain","b o b","music","primo","judge","trade","money","bulls","dunks","yahoo","video","bulls","house","spurs","stats","agent","child","trade","signs","shoes","video","draft","yahoo","quote","teams","x-men","draft","turow","video","family","father","awards","altura","braces","blocks","myteam","mother","height","salary","update","violin","videos","visina","poster","pacers","knicks","return","reddit","realgm","giants","quotes","jersey","retire","lakers","lights","latest","zasięg","israel","injury","images","top 10","author","asbury","hockey","hobbit","salary","tennis","toledo","gitaar","guitar","mother","soccer","gatech","wife","kids","king","dunk","diet","dead","heat","home","goat","gear","face","wife","logo","life","lion","cars","mask","born","espn","edit","quiz","quit","xiii","x111","info","imdb","news","nike","zoom","wiki","vine","espn","espy","team","xiii","x 11","zoom","logo","king","cavs","vine","dunk","diet","imdb","nike","next","will","vote","from","face","feet","espn","edit","body","logo","arms","diet","joke","ruby","team","quiz","wiki","meet","espn","vine","life","roto","name","nike","show","club","wife","pitt","dunk","nets","jazz","flop","iowa","espn","duke","news","espn","dunk","team","wiki","dunk","wife","cska","team","suns","espn","efes","news","vine","espn","suns","dunk","espn","eksi","ekşi","wiki","wife","facts","funny","actor","agent","bulls","movie","music","memes","money","house","draft","stats","under","prime","shoes","spurs","rings","young","yahoo","yeezy","worth","teeth","spurs","stats","umass","maine","umich","age","son","kia","dad","gif","mom","mvp","xii","xiv","ppg","png","usa","e60","gif","ppg","kia","the","nba","car","bio","gif","age","dad","mvp","mix","mom","okc","ppg","png","say","nba","nba","son","bmx","mlb","nfl","usc","nba","lsu","lmu","age","inc","mix","nba","now","nfl","nba","nba","age","mix","kid","son","gif","sig","lnb","plk","book","espn","news","dunk","diet","cavs","utep","cars","shaq","quiz","jump","edit","life","wiki","team","tall","hudl","espn","face","utsa","golf","wife","wiki","zero","ncsa","jr","ig","on","xv","dj","vj","jr","tv","pe","ou","age","acl","mix","mom","mvp","nfl","nba","nbl","now","dad","okc","ppg","png","kid","son","gsw","gif","yao","lll","iii","bio","fbu","ibm","sap","son","jpm","gif","mma","nfl","nba","now","uw","ku","jr","md","mn"];
